name: Deploy to server     #Nombre

on: push                   #Evento

jobs:                      # Trabajos
    first_jobs:
        runs-on: ubuntu-latest

        steps:                    # Pasos
         - name: Hola Mundo
           run: echo "Hola Mundo"
           

    second_jobs:
        if: ${{ github.ref == 'refs/heads/main' }}               # Contexto
        needs: first_jobs         # Se agrega dependencia
        runs-on: ubuntu-latest

        steps:
         - name: Hola Mundo
           run: echo "Hola Mundo segundo"

